"""add email to usuarios

Revision ID: 521aa2d95cdd
Revises: 6acdedec4db4
Create Date: 2026-09-19 02:46:10.919498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521aa2d95cdd'
down_revision: Union[str, Sequence[str], None] = '6acdedec4db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Adiciona nullable primeiro — usuários que já existem não têm email ainda.
    op.add_column('usuarios', sa.Column('email', sa.String(length=255), nullable=True))
    # Preenche um valor único provisório pra cada um, baseado no username (dado de
    # teste local — numa base real isso seria uma comunicação pedindo pra confirmar
    # o email de verdade, não um placeholder). Usa "example.com" (domínio reservado
    # pra documentação, RFC 2606) e não "local.test"/"local.invalid" — esses últimos
    # usam TLDs especiais que o email-validator rejeita mesmo sem checar DNS.
    op.execute("UPDATE usuarios SET email = username || '@example.com' WHERE email IS NULL")
    op.alter_column('usuarios', 'email', nullable=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_column('usuarios', 'email')
    # ### end Alembic commands ###
