"""add totp fields to usuarios

Revision ID: 82891fd8733b
Revises: 4d9167f7d404
Create Date: 2026-09-23 12:33:31.455848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82891fd8733b'
down_revision: Union[str, Sequence[str], None] = '4d9167f7d404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    op.add_column('usuarios', sa.Column('mfa_confirmado', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'mfa_confirmado')
    op.drop_column('usuarios', 'totp_secret')
    # ### end Alembic commands ###
